import{a as L,S as w,i}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function l(r,t=1){const a=new URLSearchParams({key:"56012300-f086c257a570084238c9733eb",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});return(await L.get("https://pixabay.com/api/",{params:a})).data}const d=document.querySelector(".gallery"),u=document.querySelector(".loader"),f=document.querySelector(".load-more"),S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function P({webformatURL:r,largeImageURL:t,tags:a,likes:n,views:e,comments:o,downloads:s}){return`
    <li class="gallery-item">
      <a href="${t}" data-lightbox="gallery">
        <img src="${r}" alt="${a}" />
      </a>
      <div class="details">
        <p><strong>Likes:</strong> ${n}</p>
        <p><strong>Views:</strong> ${e}</p>
        <p><strong>Comments:</strong> ${o}</p>
        <p><strong>Downloads:</strong> ${s}</p>
      </div>
    </li>
  `}function g(r){const t=r.map(P).join("");d.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){d.innerHTML=""}function h(){u.classList.remove("hidden")}function m(){u.classList.add("hidden")}function b(){f.classList.remove("hidden")}function v(){f.classList.add("hidden")}const p=document.querySelector(".form"),M=document.querySelector(".load-more");let c=1,y="";p.addEventListener("submit",R);M.addEventListener("click",$);async function R(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(console.log("Search query:",t),!t){i.info({title:"Info",message:"Please enter a search query.",position:"topRight"});return}c=1,y=t,q(),h();try{const a=await l(t,c);if(a.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(a.hits),a.totalHits>15&&b()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{m()}p.reset()}async function $(){c+=1,h();try{const r=await l(y,c);g(r.hits);const t=Math.ceil(r.totalHits/15);c>=t&&(v(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{m()}}
//# sourceMappingURL=index.js.map
