import{a as w,S,i as s}from"./assets/vendor-DcHCnVjq.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();async function d(r,e=1){const a=new URLSearchParams({key:"56012300-f086c257a570084238c9733eb",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15});return await(await w.get("https://pixabay.com/api/",{params:a})).data}const u=document.querySelector(".gallery"),g=document.querySelector(".loader"),f=document.querySelector(".load-more"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function b({webformatURL:r,largeImageURL:e,tags:a,likes:n,views:t,comments:o,downloads:i}){return`
    <li class="gallery-item">
      <a href="${e}" data-lightbox="gallery">
        <img src="${r}" alt="${a}" />
      </a>
      <div class="details">
        <p><strong>Likes:</strong> ${n}</p>
        <p><strong>Views:</strong> ${t}</p>
        <p><strong>Comments:</strong> ${o}</p>
        <p><strong>Downloads:</strong> ${i}</p>
      </div>
    </li>
  `}function h(r){const e=r.map(b).join("");u.insertAdjacentHTML("beforeend",e),P.refresh()}function v(){u.innerHTML=""}function m(){g.classList.remove("hidden")}function y(){g.classList.add("hidden")}function q(){f.classList.remove("hidden")}function p(){f.classList.add("hidden")}const L=document.querySelector(".form"),M=document.querySelector(".load-more");let c=1,l="";L.addEventListener("submit",R);M.addEventListener("click",B);async function R(r){if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),!l){s.info({title:"Info",message:"Please enter a search query.",position:"topRight"});return}c=1,v(),p(),m();try{const e=await d(l,c);if(e.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(e.hits),e.totalHits>15&&q()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}L.reset()}async function B(){c+=1,m();try{const r=await d(l,c);h(r.hits);const e=Math.ceil(r.totalHits/15);c>=e&&(p(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),E()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}}function E(){const r=document.querySelector(".gallery-item").firstElementChild;if(!r)return;const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
